---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:

- name: test
  image: trion/ng-cli-karma:8.0.2
  commands:
  - npm install
  - ng test --watch=false --progress=false

- name: e2e
  image: trion/ng-cli-karma:8.0.2
  commands:
    - npm install
    - ng e2e

- name: build
  image: trion/ng-cli-karma:8.0.2
  commands:
    - npm install
    - npm run build

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: p2olab/polaris-frontend
    auto_tag: true

- name: docker-arm
  image: plugins/docker
  settings:
    dockerfile: Dockerfile.arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: p2olab/polaris-frontend
    auto_tag: true
    auto_tag_suffix: arm

---
kind: signature
hmac: 58aaccd193aef862418f242688920adeafc3bb8ef6f24df30928e3a0c5ed33ba

...
