# build app
FROM catchdigital/node-sass as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Docker Parent Image with nginx
FROM  arm32v7/nginx
COPY ./qemu-arm-static /usr/bin/qemu-arm-static
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

